/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMockInterviewRouteImport } from './routes/_authenticated/mock-interview'
import { Route as AuthenticatedJobMatchRouteImport } from './routes/_authenticated/job-match'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedHealthScoreRouteImport } from './routes/_authenticated/health-score'
import { Route as AuthenticatedGithubResumeRouteImport } from './routes/_authenticated/github-resume'
import { Route as AuthenticatedGithubRouteImport } from './routes/_authenticated/github'
import { Route as AuthenticatedDeveloperScoreRouteImport } from './routes/_authenticated/developer-score'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCodeReviewRouteImport } from './routes/_authenticated/code-review'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortfolioDeploymentIdRouteImport } from './routes/_authenticated/portfolio-deployment.$id'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockInterviewRoute =
  AuthenticatedMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobMatchRoute = AuthenticatedJobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthScoreRoute =
  AuthenticatedHealthScoreRouteImport.update({
    id: '/health-score',
    path: '/health-score',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGithubResumeRoute =
  AuthenticatedGithubResumeRouteImport.update({
    id: '/github-resume',
    path: '/github-resume',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGithubRoute = AuthenticatedGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperScoreRoute =
  AuthenticatedDeveloperScoreRouteImport.update({
    id: '/developer-score',
    path: '/developer-score',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodeReviewRoute = AuthenticatedCodeReviewRouteImport.update({
  id: '/code-review',
  path: '/code-review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioDeploymentIdRoute =
  AuthenticatedPortfolioDeploymentIdRouteImport.update({
    id: '/portfolio-deployment/$id',
    path: '/portfolio-deployment/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/code-review': typeof AuthenticatedCodeReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer-score': typeof AuthenticatedDeveloperScoreRoute
  '/github': typeof AuthenticatedGithubRoute
  '/github-resume': typeof AuthenticatedGithubResumeRoute
  '/health-score': typeof AuthenticatedHealthScoreRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/job-match': typeof AuthenticatedJobMatchRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/p/$id': typeof PIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/portfolio-deployment/$id': typeof AuthenticatedPortfolioDeploymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/code-review': typeof AuthenticatedCodeReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer-score': typeof AuthenticatedDeveloperScoreRoute
  '/github': typeof AuthenticatedGithubRoute
  '/github-resume': typeof AuthenticatedGithubResumeRoute
  '/health-score': typeof AuthenticatedHealthScoreRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/job-match': typeof AuthenticatedJobMatchRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/p/$id': typeof PIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/portfolio-deployment/$id': typeof AuthenticatedPortfolioDeploymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/code-review': typeof AuthenticatedCodeReviewRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer-score': typeof AuthenticatedDeveloperScoreRoute
  '/_authenticated/github': typeof AuthenticatedGithubRoute
  '/_authenticated/github-resume': typeof AuthenticatedGithubResumeRoute
  '/_authenticated/health-score': typeof AuthenticatedHealthScoreRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/job-match': typeof AuthenticatedJobMatchRoute
  '/_authenticated/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/p/$id': typeof PIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/portfolio-deployment/$id': typeof AuthenticatedPortfolioDeploymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/code-review'
    | '/dashboard'
    | '/developer-score'
    | '/github'
    | '/github-resume'
    | '/health-score'
    | '/interview'
    | '/job-match'
    | '/mock-interview'
    | '/profile'
    | '/resume'
    | '/roadmap'
    | '/p/$id'
    | '/admin/analytics'
    | '/admin/usage'
    | '/portfolio-deployment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/code-review'
    | '/dashboard'
    | '/developer-score'
    | '/github'
    | '/github-resume'
    | '/health-score'
    | '/interview'
    | '/job-match'
    | '/mock-interview'
    | '/profile'
    | '/resume'
    | '/roadmap'
    | '/p/$id'
    | '/admin/analytics'
    | '/admin/usage'
    | '/portfolio-deployment/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/code-review'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer-score'
    | '/_authenticated/github'
    | '/_authenticated/github-resume'
    | '/_authenticated/health-score'
    | '/_authenticated/interview'
    | '/_authenticated/job-match'
    | '/_authenticated/mock-interview'
    | '/_authenticated/profile'
    | '/_authenticated/resume'
    | '/_authenticated/roadmap'
    | '/p/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/usage'
    | '/_authenticated/portfolio-deployment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PIdRoute: typeof PIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-interview': {
      id: '/_authenticated/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof AuthenticatedMockInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-match': {
      id: '/_authenticated/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof AuthenticatedJobMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-score': {
      id: '/_authenticated/health-score'
      path: '/health-score'
      fullPath: '/health-score'
      preLoaderRoute: typeof AuthenticatedHealthScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/github-resume': {
      id: '/_authenticated/github-resume'
      path: '/github-resume'
      fullPath: '/github-resume'
      preLoaderRoute: typeof AuthenticatedGithubResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/github': {
      id: '/_authenticated/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof AuthenticatedGithubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer-score': {
      id: '/_authenticated/developer-score'
      path: '/developer-score'
      fullPath: '/developer-score'
      preLoaderRoute: typeof AuthenticatedDeveloperScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code-review': {
      id: '/_authenticated/code-review'
      path: '/code-review'
      fullPath: '/code-review'
      preLoaderRoute: typeof AuthenticatedCodeReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio-deployment/$id': {
      id: '/_authenticated/portfolio-deployment/$id'
      path: '/portfolio-deployment/$id'
      fullPath: '/portfolio-deployment/$id'
      preLoaderRoute: typeof AuthenticatedPortfolioDeploymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCodeReviewRoute: typeof AuthenticatedCodeReviewRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperScoreRoute: typeof AuthenticatedDeveloperScoreRoute
  AuthenticatedGithubRoute: typeof AuthenticatedGithubRoute
  AuthenticatedGithubResumeRoute: typeof AuthenticatedGithubResumeRoute
  AuthenticatedHealthScoreRoute: typeof AuthenticatedHealthScoreRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedJobMatchRoute: typeof AuthenticatedJobMatchRoute
  AuthenticatedMockInterviewRoute: typeof AuthenticatedMockInterviewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedPortfolioDeploymentIdRoute: typeof AuthenticatedPortfolioDeploymentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCodeReviewRoute: AuthenticatedCodeReviewRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperScoreRoute: AuthenticatedDeveloperScoreRoute,
  AuthenticatedGithubRoute: AuthenticatedGithubRoute,
  AuthenticatedGithubResumeRoute: AuthenticatedGithubResumeRoute,
  AuthenticatedHealthScoreRoute: AuthenticatedHealthScoreRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedJobMatchRoute: AuthenticatedJobMatchRoute,
  AuthenticatedMockInterviewRoute: AuthenticatedMockInterviewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedPortfolioDeploymentIdRoute:
    AuthenticatedPortfolioDeploymentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PIdRoute: PIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
